name: .NET Core Desktop

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-latest

    env:
      Solution_Name: TeraFinder.sln

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.1

    - name: Checkout PKHeX.Core
      uses: actions/checkout@v3
      with:
        repository: kwsch/PKHeX
        ref: enc-local
        path: PKHeX

    - name: Build PKHeX.Core
      run: |
        cd PKHeX/PKHeX.Core
        dotnet restore
        msbuild PKHeX.Core.csproj /p:Configuration=Release

    - name: Restore NuGet packages
      run: dotnet restore

    - name: Replace latest PKHeX.Core NuGet
      shell: pwsh
      run: |
        $NuGetPackageFolder = Join-Path -Path $env:USERPROFILE -ChildPath ".nuget\packages\pkhex.core"
        $LatestVersion = (Get-ChildItem $NuGetPackageFolder | Sort-Object -Property LastWriteTime -Descending)[0].Name
        $PkhexCoreDllSource = Join-Path -Path $env:GITHUB_WORKSPACE -ChildPath "PKHeX/PKHeX.Core/bin/Release/net7.0/PKHeX.Core.dll"
        $PkhexCoreDllDest = Join-Path -Path $NuGetPackageFolder -ChildPath "$LatestVersion/lib/net7.0/PKHeX.Core.dll"
        Copy-Item -Path $PkhexCoreDllSource -Destination $PkhexCoreDllDest  

    - name: Execute unit tests
      run: dotnet test

    - name: Restore the application
      run: msbuild $env:Solution_Name /t:Restore /p:Configuration=$env:Configuration
      env:
        Configuration: ${{ matrix.configuration }}
        
    - name: Create the app package
      run: msbuild $env:Solution_Name /property:Configuration=Release

    - name: Upload Launcher artifacts
      uses: actions/upload-artifact@v3
      with:
        name: TeraFinder.Launcher
        path: TeraFinder.Launcher/bin

    - name: Upload Plugins artifacts
      uses: actions/upload-artifact@v3
      with:
        name: TeraFinder.Plugins
        path: |
          TeraFinder.Plugins/bin
          !TeraFinder.Plugins/bin/Release/net7.0-windows/PKHeX.Core.dll
          !TeraFinder.Plugins/bin/Release/net7.0-windows/PKHeX.Drawing.dll
          !TeraFinder.Plugins/bin/Release/net7.0-windows/PKHeX.Drawing.PokeSprite.dll